let Query = 
{        
    CariHarInsert: 
    {
        query : "INSERT INTO [dbo].[CARI_HESAP_HAREKETLERI] ( " +
                " [cha_Guid] " +
                ",[cha_DBCno] " + 
                ",[cha_SpecRecNo] " +
                ",[cha_iptal] " +
                ",[cha_fileid] " +
                ",[cha_hidden] " +
                ",[cha_kilitli] " +
                ",[cha_degisti] " +
                ",[cha_CheckSum] " +
                ",[cha_create_user] " +
                ",[cha_create_date] " +
                ",[cha_lastup_user] " +
                ",[cha_lastup_date] " +
                ",[cha_special1] " +
                ",[cha_special2] " +
                ",[cha_special3] " +
                ",[cha_firmano] " +
                ",[cha_subeno] " +
                ",[cha_evrak_tip] " +
                ",[cha_evrakno_seri] " +
                ",[cha_evrakno_sira] " +
                ",[cha_satir_no] " +
                ",[cha_tarihi] " +
                ",[cha_tip] " +
                ",[cha_cinsi] " +
                ",[cha_normal_Iade] " +
                ",[cha_tpoz] " +
                ",[cha_ticaret_turu] " +
                ",[cha_belge_no] " +
                ",[cha_belge_tarih] " +
                ",[cha_aciklama] " +
                ",[cha_satici_kodu] " +
                ",[cha_EXIMkodu] " +
                ",[cha_projekodu] " +
                ",[cha_yat_tes_kodu] " +
                ",[cha_cari_cins] " +
                ",[cha_kod] " +
                ",[cha_ciro_cari_kodu] " +
                ",[cha_d_cins] " +
                ",[cha_d_kur] " +
                ",[cha_altd_kur] " +
                ",[cha_grupno] " +
                ",[cha_srmrkkodu] " +
                ",[cha_kasa_hizmet] " +
                ",[cha_kasa_hizkod] " +
                ",[cha_karsidcinsi] " +
                ",[cha_karsid_kur] " +
                ",[cha_karsidgrupno] " +
                ",[cha_karsisrmrkkodu] " +
                ",[cha_miktari] " +
                ",[cha_meblag] " +
                ",[cha_aratoplam] " +
                ",[cha_vade] " +
                ",[cha_Vade_Farki_Yuz] " +
                ",[cha_ft_iskonto1] " +
                ",[cha_ft_iskonto2] " +
                ",[cha_ft_iskonto3] " +
                ",[cha_ft_iskonto4] " +
                ",[cha_ft_iskonto5] " +
                ",[cha_ft_iskonto6] " +
                ",[cha_ft_masraf1] " +
                ",[cha_ft_masraf2] " +
                ",[cha_ft_masraf3] " +
                ",[cha_ft_masraf4] " +
                ",[cha_isk_mas1] " +
                ",[cha_isk_mas2] " +
                ",[cha_isk_mas3] " +
                ",[cha_isk_mas4] " +
                ",[cha_isk_mas5] " +
                ",[cha_isk_mas6] " +
                ",[cha_isk_mas7] " +
                ",[cha_isk_mas8] " +
                ",[cha_isk_mas9] " +
                ",[cha_isk_mas10] " +
                ",[cha_sat_iskmas1] " +
                ",[cha_sat_iskmas2] " +
                ",[cha_sat_iskmas3] " +
                ",[cha_sat_iskmas4] " +
                ",[cha_sat_iskmas5] " +
                ",[cha_sat_iskmas6] " +
                ",[cha_sat_iskmas7] " +
                ",[cha_sat_iskmas8] " +
                ",[cha_sat_iskmas9] " +
                ",[cha_sat_iskmas10] " +
                ",[cha_yuvarlama] " +
                ",[cha_StFonPntr] " +
                ",[cha_stopaj] " +
                ",[cha_savsandesfonu] " +
                ",[cha_avansmak_damgapul] " +
                ",[cha_vergipntr] " +
                ",[cha_vergi1] " +
                ",[cha_vergi2] " +
                ",[cha_vergi3] " +
                ",[cha_vergi4] " +
                ",[cha_vergi5] " +
                ",[cha_vergi6] " +
                ",[cha_vergi7] " +
                ",[cha_vergi8] " +
                ",[cha_vergi9] " +
                ",[cha_vergi10] " +
                ",[cha_vergisiz_fl] " +
                ",[cha_otvtutari] " +
                ",[cha_otvvergisiz_fl] " +
                ",[cha_oiv_pntr] " +
                ",[cha_oivtutari] " +
                ",[cha_oiv_vergi] " +
                ",[cha_oivergisiz_fl] " +
                ",[cha_fis_tarih] " +
                ",[cha_fis_sirano] " +
                ",[cha_trefno] " +
                ",[cha_sntck_poz] " +
                ",[cha_reftarihi] " +
                ",[cha_istisnakodu] " +
                ",[cha_pos_hareketi] " +
                ",[cha_meblag_ana_doviz_icin_gecersiz_fl] " +
                ",[cha_meblag_alt_doviz_icin_gecersiz_fl] " +
                ",[cha_meblag_orj_doviz_icin_gecersiz_fl] " +
                ",[cha_sip_uid] " +
                ",[cha_kirahar_uid] " +
                ",[cha_vardiya_tarihi] " +
                ",[cha_vardiya_no] " +
                ",[cha_vardiya_evrak_ti] " +
                ",[cha_ebelge_turu] " +
                ",[cha_tevkifat_toplam] " +
                ",[cha_ilave_edilecek_kdv1] " +
                ",[cha_ilave_edilecek_kdv2] " +
                ",[cha_ilave_edilecek_kdv3] " +
                ",[cha_ilave_edilecek_kdv4] " +
                ",[cha_ilave_edilecek_kdv5] " +
                ",[cha_ilave_edilecek_kdv6] " +
                ",[cha_ilave_edilecek_kdv7] " +
                ",[cha_ilave_edilecek_kdv8] " +
                ",[cha_ilave_edilecek_kdv9] " +
                ",[cha_ilave_edilecek_kdv10] " +
                ",[cha_e_islem_turu] " +
                ",[cha_fatura_belge_turu] " +
                ",[cha_diger_belge_adi] " +
                ",[cha_uuid] " +
                ",[cha_adres_no] " +
                ",[cha_vergifon_toplam] " +
                ",[cha_ilk_belge_tarihi] " +
                ",[cha_ilk_belge_doviz_kuru] " +
                ",[cha_HareketGrupKodu1] " +
                ",[cha_HareketGrupKodu2] " +
                ",[cha_HareketGrupKodu3] " +
                ",[cha_ebelgeno_seri] " +
                ",[cha_ebelgeno_sira] " +
                ",[cha_hubid] " +
                ",[cha_hubglbid] " +
                ",[cha_disyazilimid] " +
                ") VALUES ( " +
                " @cha_Guid " +
                ",@cha_DBCno " +
                ",@cha_SpecRecNo " +
                ",@cha_iptal " +
                ",@cha_fileid " +
                ",@cha_hidden " +
                ",@cha_kilitli " +
                ",@cha_degisti " +
                ",@cha_CheckSum " +
                ",@cha_create_user " +
                ",GETDATE() " +
                ",@cha_lastup_user " +
                ",GETDATE() " +
                ",@cha_special1 " +	
                ",@cha_special2 " +
                ",@cha_special3 " +
                ",@cha_firmano " +
                ",@cha_subeno " +
                ",@cha_evrak_tip " +
                ",@cha_evrakno_seri " +
                ",@cha_evrakno_sira " +
                ",@cha_satir_no " +
                ",@cha_tarihi " +
                ",@cha_tip " +
                ",@cha_cinsi " +
                ",@cha_normal_Iade " +
                ",@cha_tpoz " +
                ",@cha_ticaret_turu " +
                ",@cha_belge_no " +
                ",@cha_belge_tarih " +
                ",@cha_aciklama " +
                ",@cha_satici_kodu " +
                ",@cha_EXIMkodu " +
                ",@cha_projekodu " +
                ",@cha_yat_tes_kodu " +
                ",@cha_cari_cins " +
                ",@cha_kod " +
                ",@cha_ciro_cari_kodu " +
                ",@cha_d_cins " +
                ",@cha_d_kur " +
                ",@cha_altd_kur " +
                ",@cha_grupno " +
                ",@cha_srmrkkodu " +
                ",@cha_kasa_hizmet " +
                ",@cha_kasa_hizkod " +
                ",@cha_karsidcinsi " +
                ",@cha_karsid_kur " +
                ",@cha_karsidgrupno " +
                ",@cha_karsisrmrkkodu " +
                ",@cha_miktari " +
                ",@cha_meblag " +
                ",@cha_aratoplam " +
                ",@cha_vade " +
                ",@cha_Vade_Farki_Yuz " +
                ",@cha_ft_iskonto1 " +
                ",@cha_ft_iskonto2 " +
                ",@cha_ft_iskonto3 " +
                ",@cha_ft_iskonto4 " +
                ",@cha_ft_iskonto5 " +
                ",@cha_ft_iskonto6 " +
                ",@cha_ft_masraf1 " +
                ",@cha_ft_masraf2 " +
                ",@cha_ft_masraf3 " +
                ",@cha_ft_masraf4 " +
                ",@cha_isk_mas1 " +
                ",@cha_isk_mas2 " +
                ",@cha_isk_mas3 " +
                ",@cha_isk_mas4 " +
                ",@cha_isk_mas5 " +
                ",@cha_isk_mas6 " +
                ",@cha_isk_mas7 " +
                ",@cha_isk_mas8 " +
                ",@cha_isk_mas9 " +
                ",@cha_isk_mas10 " +
                ",@cha_sat_iskmas1 " +
                ",@cha_sat_iskmas2 " +
                ",@cha_sat_iskmas3 " +
                ",@cha_sat_iskmas4 " +
                ",@cha_sat_iskmas5 " +
                ",@cha_sat_iskmas6 " +
                ",@cha_sat_iskmas7 " +
                ",@cha_sat_iskmas8 " +
                ",@cha_sat_iskmas9 " +
                ",@cha_sat_iskmas10 " +
                ",@cha_yuvarlama " +
                ",@cha_StFonPntr " +
                ",@cha_stopaj " +
                ",@cha_savsandesfonu " +
                ",@cha_avansmak_damgapul " +
                ",@cha_vergipntr " +
                ",@cha_vergi1 " +
                ",@cha_vergi2 " +
                ",@cha_vergi3 " +
                ",@cha_vergi4 " +
                ",@cha_vergi5 " +
                ",@cha_vergi6 " +
                ",@cha_vergi7 " +
                ",@cha_vergi8 " +
                ",@cha_vergi9 " +
                ",@cha_vergi10 " +
                ",@cha_vergisiz_fl " +
                ",@cha_otvtutari " +
                ",@cha_otvvergisiz_fl " +
                ",@cha_oiv_pntr " +
                ",@cha_oivtutari " +
                ",@cha_oiv_vergi " +
                ",@cha_oivergisiz_fl " +
                ",@cha_fis_tarih " +
                ",@cha_fis_sirano " +
                ",@cha_trefno " +
                ",@cha_sntck_poz " +
                ",@cha_reftarihi " +
                ",@cha_istisnakodu " +
                ",@cha_pos_hareketi " +
                ",@cha_meblag_ana_doviz_icin_gecersiz_fl " +
                ",@cha_meblag_alt_doviz_icin_gecersiz_fl " +
                ",@cha_meblag_orj_doviz_icin_gecersiz_fl " +
                ",@cha_sip_uid " +
                ",@cha_kirahar_uid " +
                ",@cha_vardiya_tarihi " +
                ",@cha_vardiya_no " +
                ",@cha_vardiya_evrak_ti " +
                ",@cha_ebelge_turu " +
                ",@cha_tevkifat_toplam " +
                ",@cha_ilave_edilecek_kdv1 " +
                ",@cha_ilave_edilecek_kdv2 " +
                ",@cha_ilave_edilecek_kdv3 " +
                ",@cha_ilave_edilecek_kdv4 " +
                ",@cha_ilave_edilecek_kdv5 " +
                ",@cha_ilave_edilecek_kdv6 " +
                ",@cha_ilave_edilecek_kdv7 " +
                ",@cha_ilave_edilecek_kdv8 " +
                ",@cha_ilave_edilecek_kdv9 " +
                ",@cha_ilave_edilecek_kdv10 " +
                ",@cha_e_islem_turu " +
                ",@cha_fatura_belge_turu " +
                ",@cha_diger_belge_adi " +
                ",@cha_uuid " +
                ",@cha_adres_no " +
                ",@cha_vergifon_toplam " +
                ",@cha_ilk_belge_tarihi " +
                ",@cha_ilk_belge_doviz_kuru " +
                ",@cha_HareketGrupKodu1 " +
                ",@cha_HareketGrupKodu2 " +
                ",@cha_HareketGrupKodu3 " +
                ",@cha_ebelgeno_seri " +
                ",@cha_ebelgeno_sira " +
                ",@cha_hubid " +
                ",@cha_hubglbid " +
                ",@cha_disyazilimid " +
                ")",
        param : ['cha_Guid:string|50','cha_DBCno:int','cha_SpecRecNo:int','cha_iptal:bit','cha_fileid:int','cha_hidden:bit','cha_kilitli:bit','cha_degisti:bit','cha_CheckSum:int',
                 'cha_create_user:int','cha_lastup_user:int','cha_special1:string|4','cha_special2:string|4','cha_special3:string|4','cha_firmano:int','cha_subeno:int','cha_evrak_tip:int',
                 'cha_evrakno_seri:string|20','cha_evrakno_sira:int','cha_satir_no:int','cha_tarihi:date','cha_tip:int','cha_cinsi:int','cha_normal_Iade:int','cha_tpoz:int',
                 'cha_ticaret_turu:int','cha_belge_no:string|50','cha_belge_tarih:date','cha_aciklama:string|40','cha_satici_kodu:string|25','cha_EXIMkodu:string|25','cha_projekodu:string|25','cha_yat_tes_kodu:string|25',
                 'cha_cari_cins:int','cha_kod:string|25','cha_ciro_cari_kodu:string|25','cha_d_cins:int','cha_d_kur:float','cha_altd_kur:float','cha_grupno:int','cha_srmrkkodu:string|25','cha_kasa_hizmet:int',
                 'cha_kasa_hizkod:string|25','cha_karsidcinsi:int','cha_karsid_kur:float','cha_karsidgrupno:int','cha_karsisrmrkkodu:string|25','cha_miktari:float','cha_meblag:float','cha_aratoplam:float',
                 'cha_vade:int','cha_Vade_Farki_Yuz:float','cha_ft_iskonto1:float','cha_ft_iskonto2:float','cha_ft_iskonto3:float','cha_ft_iskonto4:float','cha_ft_iskonto5:float','cha_ft_iskonto6:float',
                 'cha_ft_masraf1:float','cha_ft_masraf2:float','cha_ft_masraf3:float','cha_ft_masraf4:float','cha_isk_mas1:int','cha_isk_mas2:int','cha_isk_mas3:int','cha_isk_mas4:int','cha_isk_mas5:int',
                 'cha_isk_mas6:int','cha_isk_mas7:int','cha_isk_mas8:int','cha_isk_mas9:int','cha_isk_mas10:int','cha_sat_iskmas1:bit','cha_sat_iskmas2:bit','cha_sat_iskmas3:bit','cha_sat_iskmas4:bit',
                 'cha_sat_iskmas5:bit','cha_sat_iskmas6:bit','cha_sat_iskmas7:bit','cha_sat_iskmas8:bit','cha_sat_iskmas9:bit','cha_sat_iskmas10:bit','cha_yuvarlama:float','cha_StFonPntr:int','cha_stopaj:float',
                 'cha_savsandesfonu:float','cha_avansmak_damgapul:float','cha_vergipntr:int','cha_vergi1:float','cha_vergi2:float','cha_vergi3:float','cha_vergi4:float','cha_vergi5:float','cha_vergi6:float',
                 'cha_vergi7:float','cha_vergi8:float','cha_vergi9:float','cha_vergi10:float','cha_vergisiz_fl:bit','cha_otvtutari:float','cha_otvvergisiz_fl:bit','cha_oiv_pntr:int','cha_oivtutari:float',
                 'cha_oiv_vergi:float','cha_oivergisiz_fl:bit','cha_fis_tarih:date','cha_fis_sirano:int','cha_trefno:string|25','cha_sntck_poz:int','cha_reftarihi:date','cha_istisnakodu:int','cha_pos_hareketi:int',
                 'cha_meblag_ana_doviz_icin_gecersiz_fl:int','cha_meblag_alt_doviz_icin_gecersiz_fl:int','cha_meblag_orj_doviz_icin_gecersiz_fl:int','cha_sip_uid:string|50','cha_kirahar_uid:string|50','cha_vardiya_tarihi:date',
                 'cha_vardiya_no:int','cha_vardiya_evrak_ti:int','cha_ebelge_turu:int','cha_tevkifat_toplam:float','cha_ilave_edilecek_kdv1:float','cha_ilave_edilecek_kdv2:float','cha_ilave_edilecek_kdv3:float',
                 'cha_ilave_edilecek_kdv4:float','cha_ilave_edilecek_kdv5:float','cha_ilave_edilecek_kdv6:float','cha_ilave_edilecek_kdv7:float','cha_ilave_edilecek_kdv8:float','cha_ilave_edilecek_kdv9:float',
                 'cha_ilave_edilecek_kdv10:float','cha_e_islem_turu:int','cha_fatura_belge_turu:int','cha_diger_belge_adi:string|50','cha_uuid:string|40','cha_adres_no:int','cha_vergifon_toplam:float','cha_ilk_belge_tarihi:date',
                 'cha_ilk_belge_doviz_kuru:float','cha_HareketGrupKodu1:string|25','cha_HareketGrupKodu2:string|25','cha_HareketGrupKodu3:string|25','cha_ebelgeno_seri:string|20','cha_ebelgeno_sira:int','cha_hubid:string|50',
                 'cha_hubglbid:string|50','cha_disyazilimid:string|50']
    },
    StokHarInsert: 
    {
        query : "INSERT INTO [dbo].[STOK_HAREKETLERI] ( " +
                " [sth_Guid] " +
                ",[sth_DBCno] " +
                ",[sth_SpecRECno] " +
                ",[sth_iptal] " +
                ",[sth_fileid] " +
                ",[sth_hidden] " +
                ",[sth_kilitli] " +
                ",[sth_degisti] " +
                ",[sth_checksum] " +
                ",[sth_create_user] " +
                ",[sth_create_date] " +
                ",[sth_lastup_user] " +
                ",[sth_lastup_date] " +
                ",[sth_special1] " +
                ",[sth_special2] " +
                ",[sth_special3] " +
                ",[sth_firmano] " +
                ",[sth_subeno] " +
                ",[sth_tarih] " +
                ",[sth_tip] " +
                ",[sth_cins] " +
                ",[sth_normal_iade] " +
                ",[sth_evraktip] " +
                ",[sth_evrakno_seri] " +
                ",[sth_evrakno_sira] " +
                ",[sth_satirno] " +
                ",[sth_belge_no] " +
                ",[sth_belge_tarih] " +
                ",[sth_stok_kod] " +
                ",[sth_isk_mas1] " +
                ",[sth_isk_mas2] " +
                ",[sth_isk_mas3] " +
                ",[sth_isk_mas4] " +
                ",[sth_isk_mas5] " +
                ",[sth_isk_mas6] " +
                ",[sth_isk_mas7] " +
                ",[sth_isk_mas8] " +
                ",[sth_isk_mas9] " +
                ",[sth_isk_mas10] " +
                ",[sth_sat_iskmas1] " +
                ",[sth_sat_iskmas2] " +
                ",[sth_sat_iskmas3] " +
                ",[sth_sat_iskmas4] " +
                ",[sth_sat_iskmas5] " +
                ",[sth_sat_iskmas6] " +
                ",[sth_sat_iskmas7] " +
                ",[sth_sat_iskmas8] " +
                ",[sth_sat_iskmas9] " +
                ",[sth_sat_iskmas10] " +
                ",[sth_pos_satis] " +
                ",[sth_promosyon_fl] " +
                ",[sth_cari_cinsi] " +
                ",[sth_cari_kodu] " +
                ",[sth_cari_grup_no] " +
                ",[sth_isemri_gider_kodu] " +
                ",[sth_plasiyer_kodu] " +
                ",[sth_har_doviz_cinsi] " +
                ",[sth_har_doviz_kuru] " +
                ",[sth_alt_doviz_kuru] " +
                ",[sth_stok_doviz_cinsi] " +
                ",[sth_stok_doviz_kuru] " +
                ",[sth_miktar] " +
                ",[sth_miktar2] " +
                ",[sth_birim_pntr] " +
                ",[sth_tutar] " +
                ",[sth_iskonto1] " +
                ",[sth_iskonto2] " +
                ",[sth_iskonto3] " +
                ",[sth_iskonto4] " +
                ",[sth_iskonto5] " +
                ",[sth_iskonto6] " +
                ",[sth_masraf1] " +
                ",[sth_masraf2] " +
                ",[sth_masraf3] " +
                ",[sth_masraf4] " +
                ",[sth_vergi_pntr] " +
                ",[sth_vergi] " +
                ",[sth_masraf_vergi_pntr] " +
                ",[sth_masraf_vergi] " +
                ",[sth_netagirlik] " +
                ",[sth_odeme_op] " +
                ",[sth_aciklama] " +
                ",[sth_sip_uid] " +
                ",[sth_fat_uid] " +
                ",[sth_giris_depo_no] " +
                ",[sth_cikis_depo_no] " +
                ",[sth_malkbl_sevk_tarihi] " +
                ",[sth_cari_srm_merkezi] " +
                ",[sth_stok_srm_merkezi] " +
                ",[sth_fis_tarihi] " +
                ",[sth_fis_sirano] " +
                ",[sth_vergisiz_fl] " +
                ",[sth_maliyet_ana] " +
                ",[sth_maliyet_alternatif] " +
                ",[sth_maliyet_orjinal] " +
                ",[sth_adres_no] " +
                ",[sth_parti_kodu] " +
                ",[sth_lot_no] " +
                ",[sth_kons_uid] " +
                ",[sth_proje_kodu] " +
                ",[sth_exim_kodu] " +
                ",[sth_otv_pntr] " +
                ",[sth_otv_vergi] " +
                ",[sth_brutagirlik] " +
                ",[sth_disticaret_turu] " +
                ",[sth_otvtutari] " +
                ",[sth_otvvergisiz_fl] " +
                ",[sth_oiv_pntr] " +
                ",[sth_oiv_vergi] " +
                ",[sth_oivvergisiz_fl] " +
                ",[sth_fiyat_liste_no] " +
                ",[sth_oivtutari] " +
                ",[sth_Tevkifat_turu] " +
                ",[sth_nakliyedeposu] " +
                ",[sth_nakliyedurumu] " +
                ",[sth_yetkili_uid] " +
                ",[sth_taxfree_fl] " +
                ",[sth_ilave_edilecek_kdv] " +
                ",[sth_ismerkezi_kodu] " +
                ",[sth_HareketGrupKodu1] " +
                ",[sth_HareketGrupKodu2] " +
                ",[sth_HareketGrupKodu3] " +
                ",[sth_Olcu1] " +
                ",[sth_Olcu2] " +
                ",[sth_Olcu3] " +
                ",[sth_Olcu4] " +
                ",[sth_Olcu5] " +
                ",[sth_FormulMiktarNo] " +
                ",[sth_FormulMiktar] " +
                ",[sth_eirs_senaryo] " +
                ",[sth_eirs_tipi] " +
                ",[sth_teslim_tarihi] " +
                ",[sth_matbu_fl] " +
                ") VALUES ( " +
                " @sth_Guid " +
                ",@sth_DBCno " +
                ",@sth_SpecRECno " +
                ",@sth_iptal " +
                ",@sth_fileid " +
                ",@sth_hidden " +
                ",@sth_kilitli " +
                ",@sth_degisti " +
                ",@sth_checksum " +
                ",@sth_create_user " +
                ",GETDATE() " +
                ",@sth_lastup_user " +
                ",GETDATE() " +
                ",@sth_special1 " +
                ",@sth_special2 " +
                ",@sth_special3 " +
                ",@sth_firmano " +
                ",@sth_subeno " +
                ",@sth_tarih " +
                ",@sth_tip " +
                ",@sth_cins " +
                ",@sth_normal_iade " +
                ",@sth_evraktip " +
                ",@sth_evrakno_seri " +
                ",@sth_evrakno_sira " +
                ",@sth_satirno " +
                ",@sth_belge_no " +
                ",@sth_belge_tarih " +
                ",@sth_stok_kod " +
                ",@sth_isk_mas1 " +
                ",@sth_isk_mas2 " +
                ",@sth_isk_mas3 " +
                ",@sth_isk_mas4 " +
                ",@sth_isk_mas5 " +
                ",@sth_isk_mas6 " +
                ",@sth_isk_mas7 " +
                ",@sth_isk_mas8 " +
                ",@sth_isk_mas9 " +
                ",@sth_isk_mas10 " +
                ",@sth_sat_iskmas1 " +
                ",@sth_sat_iskmas2 " +
                ",@sth_sat_iskmas3 " +
                ",@sth_sat_iskmas4 " +
                ",@sth_sat_iskmas5 " +
                ",@sth_sat_iskmas6 " +
                ",@sth_sat_iskmas7 " +
                ",@sth_sat_iskmas8 " +
                ",@sth_sat_iskmas9 " +
                ",@sth_sat_iskmas10 " +
                ",@sth_pos_satis " +
                ",@sth_promosyon_fl " +
                ",@sth_cari_cinsi " +
                ",@sth_cari_kodu " +
                ",@sth_cari_grup_no " +
                ",@sth_isemri_gider_kodu " +
                ",@sth_plasiyer_kodu " +
                ",@sth_har_doviz_cinsi " +
                ",@sth_har_doviz_kuru " +
                ",@sth_alt_doviz_kuru " +
                ",@sth_stok_doviz_cinsi " +
                ",@sth_stok_doviz_kuru " +
                ",@sth_miktar " +
                ",@sth_miktar2 " +
                ",@sth_birim_pntr " +
                ",@sth_tutar " +
                ",@sth_iskonto1 " +
                ",@sth_iskonto2 " +
                ",@sth_iskonto3 " +
                ",@sth_iskonto4 " +
                ",@sth_iskonto5 " +
                ",@sth_iskonto6 " +
                ",@sth_masraf1 " +
                ",@sth_masraf2 " +
                ",@sth_masraf3 " +
                ",@sth_masraf4 " +
                ",@sth_vergi_pntr " +
                ",@sth_vergi " +
                ",@sth_masraf_vergi_pntr " +
                ",@sth_masraf_vergi " +
                ",@sth_netagirlik " +
                ",@sth_odeme_op " +
                ",@sth_aciklama " +
                ",@sth_sip_uid " +
                ",@sth_fat_uid " +
                ",@sth_giris_depo_no " +
                ",@sth_cikis_depo_no " +
                ",@sth_malkbl_sevk_tarihi " +
                ",@sth_cari_srm_merkezi " +
                ",@sth_stok_srm_merkezi " +
                ",@sth_fis_tarihi " +
                ",@sth_fis_sirano " +
                ",@sth_vergisiz_fl " +
                ",@sth_maliyet_ana " +
                ",@sth_maliyet_alternatif " +
                ",@sth_maliyet_orjinal " +
                ",@sth_adres_no " +
                ",@sth_parti_kodu " +
                ",@sth_lot_no " +
                ",@sth_kons_uid " +
                ",@sth_proje_kodu " +
                ",@sth_exim_kodu " +
                ",@sth_otv_pntr " +
                ",@sth_otv_vergi " +
                ",@sth_brutagirlik " +
                ",@sth_disticaret_turu " +
                ",@sth_otvtutari " +
                ",@sth_otvvergisiz_fl " +
                ",@sth_oiv_pntr " +
                ",@sth_oiv_vergi " +
                ",@sth_oivvergisiz_fl " +
                ",@sth_fiyat_liste_no " +
                ",@sth_oivtutari " +
                ",@sth_Tevkifat_turu " +
                ",@sth_nakliyedeposu " +
                ",@sth_nakliyedurumu " +
                ",@sth_yetkili_uid " +
                ",@sth_taxfree_fl " +
                ",@sth_ilave_edilecek_kdv " +
                ",@sth_ismerkezi_kodu " +
                ",@sth_HareketGrupKodu1 " +
                ",@sth_HareketGrupKodu2 " +
                ",@sth_HareketGrupKodu3 " +
                ",@sth_Olcu1 " +
                ",@sth_Olcu2 " +
                ",@sth_Olcu3 " +
                ",@sth_Olcu4 " +
                ",@sth_Olcu5 " +
                ",@sth_FormulMiktarNo " +
                ",@sth_FormulMiktar " +
                ",@sth_eirs_senaryo " +
                ",@sth_eirs_tipi " +
                ",@sth_teslim_tarihi " +
                ",@sth_matbu_fl " +
                ")",
        param : ['sth_Guid:string|50','sth_DBCno:int','sth_SpecRECno:int','sth_iptal:bit','sth_fileid:int','sth_hidden:bit','sth_kilitli:bit','sth_degisti:bit','sth_checksum:int',
                'sth_create_user:int','sth_lastup_user:int','sth_special1:string|4','sth_special2:string|4','sth_special3:string|4','sth_firmano:int','sth_subeno:int','sth_tarih:date',
                'sth_tip:int','sth_cins:int','sth_normal_iade:int','sth_evraktip:int','sth_evrakno_seri:string|20','sth_evrakno_sira:int','sth_satirno:int','sth_belge_no:string|50',
                'sth_belge_tarih:date','sth_stok_kod:string|25','sth_isk_mas1:int','sth_isk_mas2:int','sth_isk_mas3:int','sth_isk_mas4:int','sth_isk_mas5:int','sth_isk_mas6:int',
                'sth_isk_mas7:int','sth_isk_mas8:int','sth_isk_mas9:int','sth_isk_mas10:int','sth_sat_iskmas1:bit','sth_sat_iskmas2:bit','sth_sat_iskmas3:bit','sth_sat_iskmas4:bit',
                'sth_sat_iskmas5:bit','sth_sat_iskmas6:bit','sth_sat_iskmas7:bit','sth_sat_iskmas8:bit','sth_sat_iskmas9:bit','sth_sat_iskmas10:bit','sth_pos_satis:int','sth_promosyon_fl:bit',
                'sth_cari_cinsi:int','sth_cari_kodu:string|25','sth_cari_grup_no:int','sth_isemri_gider_kodu:string|25','sth_plasiyer_kodu:string|25','sth_har_doviz_cinsi:float','sth_har_doviz_kuru:float',
                'sth_alt_doviz_kuru:float','sth_stok_doviz_cinsi:int','sth_stok_doviz_kuru:float','sth_miktar:float','sth_miktar2:float','sth_birim_pntr:int','sth_tutar:float','sth_iskonto1:float',
                'sth_iskonto2:float','sth_iskonto3:float','sth_iskonto4:float','sth_iskonto5:float','sth_iskonto6:float','sth_masraf1:float','sth_masraf2:float','sth_masraf3:float','sth_masraf4:float',
                'sth_vergi_pntr:int','sth_vergi:float','sth_masraf_vergi_pntr:int','sth_masraf_vergi:float','sth_netagirlik:float','sth_odeme_op:int','sth_aciklama:string|50','sth_sip_uid:string|50',
                'sth_fat_uid:string|50','sth_giris_depo_no:int','sth_cikis_depo_no:int','sth_malkbl_sevk_tarihi:date','sth_cari_srm_merkezi:string|25','sth_stok_srm_merkezi:string|25','sth_fis_tarihi:date',
                'sth_fis_sirano:int','sth_vergisiz_fl:bit','sth_maliyet_ana:float','sth_maliyet_alternatif:float','sth_maliyet_orjinal:float','sth_adres_no:int','sth_parti_kodu:string|25','sth_lot_no:int',
                'sth_kons_uid:string|50','sth_proje_kodu:string|25','sth_exim_kodu:string|25','sth_otv_pntr:int','sth_otv_vergi:float','sth_brutagirlik:float','sth_disticaret_turu:int','sth_otvtutari:float',
                'sth_otvvergisiz_fl:bit','sth_oiv_pntr:int','sth_oiv_vergi:float','sth_oivvergisiz_fl:int','sth_fiyat_liste_no:int','sth_oivtutari:float','sth_Tevkifat_turu:int',
                'sth_nakliyedeposu:int','sth_nakliyedurumu:int','sth_yetkili_uid:string|50','sth_taxfree_fl:bit','sth_ilave_edilecek_kdv:float','sth_ismerkezi_kodu:string|25',
                'sth_HareketGrupKodu1:string|25','sth_HareketGrupKodu2:string|25','sth_HareketGrupKodu3:string|25','sth_Olcu1:float','sth_Olcu2:float','sth_Olcu3:float','sth_Olcu4:float',
                'sth_Olcu5:float','sth_FormulMiktarNo:int','sth_FormulMiktar:float','sth_eirs_senaryo:int','sth_eirs_tipi:int','sth_teslim_tarihi:date','sth_matbu_fl:bit']
    }                  
}
module.exports = Query;